[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"

[functions.generate-sitemap]
  name = "generate-sitemap"
  path = "netlify/functions/generate-sitemap.js"
  events = [{ type = "http" }, { type = "scheduled", cron = "0 0 1 * *" }]
